import { IChatBox } from '../../../shared/interfaces/requests/chatbox.interface';
export const chatBoxDataArray: IChatBox[] = [
  {
    employeeId: 1,
    employeeName: 'John Doe',
    lastMessage: 'Hello, how are you?',
    isSeen: false,
    newMessages: 2,
    recieverId: 2,
    recieverName: 'Alice Smith',
    lastActive: '2024-02-09T09:59:33.976Z',
  },
  {
    employeeId: 2,
    employeeName: 'Alice Smith',
    lastMessage: "Hi John! I'm good, thanks for asking.",
    isSeen: true,
    newMessages: 0,
    recieverId: 1,
    recieverName: 'John Doe',
    lastActive: '2024-02-09T10:05:12.123Z',
  },
  {
    employeeId: 3,
    employeeName: 'Bob Johnson',
    lastMessage: 'Good morning!',
    isSeen: false,
    newMessages: 1,
    recieverId: 1,
    recieverName: 'John Doe',
    lastActive: '2024-02-09T10:15:00.000Z',
  },
  {
    employeeId: 4,
    employeeName: 'Emily Brown',
    lastMessage: 'Hey there!',
    isSeen: true,
    newMessages: 0,
    recieverId: 2,
    recieverName: 'Alice Smith',
    lastActive: '2024-02-09T10:20:45.678Z',
  },
  {
    employeeId: 5,
    employeeName: 'Michael Johnson',
    lastMessage: 'Morning!',
    isSeen: false,
    newMessages: 3,
    recieverId: 2,
    recieverName: 'Alice Smith',
    lastActive: '2024-02-09T10:25:30.987Z',
  },
  {
    employeeId: 6,
    employeeName: 'Samantha White',
    lastMessage: 'Hi everyone!',
    isSeen: false,
    newMessages: 0,
    recieverId: 1,
    recieverName: 'John Doe',
    lastActive: '2024-02-09T10:30:15.234Z',
  },
  {
    employeeId: 7,
    employeeName: 'David Miller',
    lastMessage: 'Hey folks!',
    isSeen: false,
    newMessages: 1,
    recieverId: 3,
    recieverName: 'Bob Johnson',
    lastActive: '2024-02-09T10:35:00.543Z',
  },
  {
    employeeId: 8,
    employeeName: 'Sophia Lee',
    lastMessage: 'Good evening!',
    isSeen: true,
    newMessages: 0,
    recieverId: 3,
    recieverName: 'Bob Johnson',
    lastActive: '2024-02-09T10:40:20.876Z',
  },
  {
    employeeId: 9,
    employeeName: 'Matthew Clark',
    lastMessage: 'Hello world!',
    isSeen: false,
    newMessages: 2,
    recieverId: 1,
    recieverName: 'John Doe',
    lastActive: '2024-02-09T10:45:30.987Z',
  },
  {
    employeeId: 10,
    employeeName: 'Emma Davis',
    lastMessage: 'Hi there!',
    isSeen: true,
    newMessages: 0,
    recieverId: 2,
    recieverName: 'Alice Smith',
    lastActive: '2024-02-09T10:50:40.876Z',
  },
  // Add more objects as needed
];

console.log(chatBoxDataArray);
