export const ICONS = {
  delete: {
    class: 'bi bi-trash3',
    toolTip: 'delete',
    name: 'delete',
    openDelay: 1000,
    closeDelay: 500,
  },
  deleteFilled: {
    class: 'bi bi-trash3-fill',
    toolTip: 'delete',
    name: 'delete',
    openDelay: 1000,
    closeDelay: 500,
  },
  add: {
    class: '',
    toolTip: 'delete',
    name: 'delete',
    openDelay: 1000,
    closeDelay: 500,
  },
  addFilled: {
    class: '',
    toolTip: 'delete',
    name: 'add',
    openDelay: 1000,
    closeDelay: 500,
  },
  edit: {
    class: 'bi bi-pen',
    toolTip: 'edit',
    openDelay: 1000,
    name: 'edit',
    closeDelay: 500,
  },
  editFilled: {
    class: 'bi bi-pen-fill',
    toolTip: 'edit',
    openDelay: 1000,
    name: 'edit',
    closeDelay: 500,
  },
  up: {
    class: 'bi bi-caret-up',
    toolTip: 'sort By Ascending',
    openDelay: 1000,
    name: 'up',
    closeDelay: 500,
  },
  upFilled: {
    class: 'bi bi-caret-up-fill',
    toolTip: 'sort By Ascending',
    openDelay: 1000,
    name: 'up',
    closeDelay: 500,
  },
  down: {
    class: 'bi bi-caret-down',
    toolTip: 'sort by Descending',
    openDelay: 1000,
    name: 'down',
    closeDelay: 500,
  },
  downFilled: {
    class: 'bi bi-caret-down-fill',
    toolTip: 'sort by Descending',
    openDelay: 1000,
    name: 'down',
    closeDelay: 500,
  },
  eye: {
    class: 'bi bi-eye',
    toolTip: 'view employees by department',
    openDelay: 1000,
    name: 'eye',
    closeDelay: 500,
  },
  eyeFilled: {
    class: 'bi bi-eye-fill',
    toolTip: 'view employees by department',
    openDelay: 1000,
    name: 'eye',
    closeDelay: 500,
  },
  assignTask: {
    class: 'bi bi-person-workspace',
    name: 'assignTask',
    toolTip: 'Assign Task',
    openDelay: 1000,
    closeDelay: 500,
  },
  active: {
    class: 'bi bi-square',
    name: 'todo',
    toolTip: 'mark as done',
    openDelay: 1000,
    closeDelay: 500,
  },
  done: {
    class: 'bi bi-check-square',
    name: 'todo',
    toolTip: 'mark as undone',
    openDelay: 1000,
    closeDelay: 500,
  },
  taskNotCompleted: {
    class: 'bi bi-clock-history',
    name: 'task not completed',
    toolTip: 'task not completed',
    openDelay: 1000,
    closeDelay: 500,
  },
  taskCompleted: {
    class: 'bi bi-check',
    name: 'task completed',
    toolTip: 'task completed',
    openDelay: 1000,
    closeDelay: 500,
  },
  change: {
    class: 'bi bi-check-circle-fill',
    name: 'change',
    toolTip: 'change',
    openDelay: 1000,
    closeDelay: 500,
  },
  cancel: {
    class: 'bi bi-x-circle-fill',
    name: 'cancel',
    toolTip: 'cancel',
    openDelay: 1000,
    closeDelay: 500,
  },
  chatWith: {
    class: 'bi bi-chat-dots',
    name: 'chatWith',
    toolTip: 'chatWith',
    openDelay: 1000,
    closeDelay: 500,
  },
  chatWithFilled: {
    class: 'bi bi-chat-dots-fill',
    name: 'chatWith',
    toolTip: 'chatWith',
    openDelay: 1000,
    closeDelay: 500,
  },
  notSeen: {
    class: 'bi bi-check',
    name: 'notSeen',
    toolTip: 'not seen yet',
    openDelay: 1000,
    closeDelay: 500,
  },
  seen: {
    class: 'bi bi-check-all',
    name: 'notSeen',
    toolTip: 'not seen yet',
    openDelay: 1000,
    closeDelay: 500,
  },
  scrollDown: {
    class: 'bi bi-arrow-down-circle',
    name: 'scrollDown',
    toolTip: 'not seen yet',
    openDelay: 1000,
    closeDelay: 500,
  },
  copy: {
    class: 'bi bi-copy',
    name: 'copy',
    toolTip: 'not seen yet',
    openDelay: 1000,
    closeDelay: 500,
  },
  bell: {
    class: 'bi bi-bell',
    name: 'bell',
    toolTip: 'open notifications',
    openDelay: 1000,
    closeDelay: 500,
  },
  bellFilled: {
    class: 'bi bi-bell-fill',
    name: 'bell',
    toolTip: 'close notifications',
    openDelay: 1000,
    closeDelay: 500,
  },
  emoji: {
    class: 'bi bi-emoji-grin-fill',
    name: 'emoji',
    toolTip: 'close emojis',
    openDelay: 1000,
    closeDelay: 500,
  },
  emojiFilled: {
    class: 'bi bi-emoji-grin',
    name: 'emoji',
    toolTip: 'open emojis',
    openDelay: 1000,
    closeDelay: 500,
  },
  closeTab: {
    class: 'bi bi-x-square',
    name: 'emoji',
    toolTip: 'open emojis',
    openDelay: 1000,
    closeDelay: 500,
  },
  minimizeTab: {
    class: 'bi bi-dash-square',
    name: 'emoji',
    oolTip: 'open emojis',
    openDelay: 1000,
    closeDelay: 500,
  },
  fullScreen: {
    class: 'bi bi-square',
    name: 'fullScreen',
    toolTip: 'maximize',
    openDelay: 1000,
    closeDelay: 500,
  },
  fullScreenExit: {
    class: 'bi bi-copy',
    name: 'fullScreen',
    toolTip: 'minimize',
    openDelay: 1000,
    closeDelay: 500,
  },
  search: {
    class: 'bi bi-search',
    name: 'search',
    toolTip: 'minimize',
    openDelay: 1000,
    closeDelay: 500,
  },
  tableView: {
    class: 'bi bi-grid-3x3-gap',
    name: 'tableView',
    toolTip: 'minimize',
    openDelay: 1000,
    closeDelay: 500,
  },
  tableViewFilled: {
    class: 'bi bi-grid-3x3-gap-fill',
    name: 'tableViewFilled',
    toolTip: 'minimize',
    openDelay: 1000,
    closeDelay: 500,
  },
};
